# Generated by Django 3.2.11 on 2022-01-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('my_open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('my_close', models.FloatField()),
                ('wpa', models.FloatField()),
                ('no_of_shares', models.IntegerField()),
                ('no_of_trades', models.IntegerField()),
                ('total_turn_over', models.IntegerField()),
                ('deliverable_qauntity', models.IntegerField()),
                ('p_dei_qnty_to_trade_quanty', models.FloatField()),
                ('spread_h_l', models.FloatField()),
                ('spread_c_o', models.FloatField()),
            ],
        ),
    ]
